/*
 * This file was automatically generated by EvoSuite
 * Sun Oct 25 06:07:11 GMT 2020
 */

package net.mooctest;

import org.junit.Test;
import static org.junit.Assert.*;
import net.mooctest.Edge;
import net.mooctest.Node;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Edge_ESTest extends Edge_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Node node0 = new Node();
      Edge edge0 = new Edge((String) null, node0);
      String string0 = edge0.getLabel();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Node node0 = new Node();
      Edge edge0 = new Edge("gN,2vH#!\"g0W+/6v?2", node0);
      String string0 = edge0.getLabel();
      assertEquals("gN,2vH#!\"g0W+/6v?2", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Node node0 = new Node();
      Edge edge0 = new Edge((String) null, node0);
      edge0.setDest((Node) null);
      Node node1 = edge0.getDest();
      assertNull(node1);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Node node0 = new Node();
      Edge edge0 = new Edge("", node0);
      String string0 = edge0.getLabel();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Node node0 = new Node();
      Edge edge0 = new Edge("", node0);
      Node node1 = edge0.getDest();
      assertSame(node0, node1);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Node node0 = new Node();
      Edge edge0 = new Edge("", node0);
      edge0.setLabel("");
      assertEquals("", edge0.getLabel());
  }
}
