/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 19 08:24:14 GMT 2019
 */

package net.mooctest;

import org.junit.Test;
import static org.junit.Assert.*;
import net.mooctest.CommandNotFoundException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true)
public class CommandNotFoundException_ESTest extends CommandNotFoundException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CommandNotFoundException commandNotFoundException0 = new CommandNotFoundException((String) null);
      String string0 = commandNotFoundException0.getCommand();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CommandNotFoundException commandNotFoundException0 = new CommandNotFoundException("'M[VJ.{6cb~UER9BbCj");
      String string0 = commandNotFoundException0.getCommand();
      assertEquals("'M[VJ.{6cb~UER9BbCj", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CommandNotFoundException commandNotFoundException0 = new CommandNotFoundException("");
      String string0 = commandNotFoundException0.getCommand();
      assertEquals("", string0);
  }
}
