# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/233.xdc

# IP: ip/RAM/RAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM || ORIG_REF_NAME==RAM} -quiet] -quiet
