import java.lang.Math;
import java.util.Scanner;

public class exercise4 {
    private static void print(String str) {
        System.out.print(str);
    }

    private static int get(int a, int b) {
        //Input a, b Return a ramdom number in [a, b)
        if (a > b)
            return 0;
        return (int) (Math.random() * (b - a) + a);
    }

    private static void ex4(Scanner sc) {
        int[] a = new int[5];
        int mmax, mmin;
        a[0] = get(10, 99);
        mmax = mmin = a[0];
        for (int i = 1; i < 3; ++i) {
            a[i] = get(10, 99);
            if (a[i] > mmax)
                mmax = a[i];
            if (a[i] < mmin)
                mmin = a[i];
        }
        print(String.format("The 3 random integers generated by Math.random(): %d %d %d\n", a[0], a[1], a[2]));
        print(String.format("The max value: %d\n", mmax));
        print(String.format("The max value: %d\n", mmin));
    }

    public static void main(String[] arg) {
        Scanner sc = new Scanner(System.in);
        ex4(sc);
        sc.close();
    }
}