# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/mux.xdc

# Block Designs: bd/mux/mux.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mux || ORIG_REF_NAME==mux} -quiet] -quiet

# IP: bd/mux/ip/mux_NOT_GATE_0_0_1/mux_NOT_GATE_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mux_NOT_GATE_0_0 || ORIG_REF_NAME==mux_NOT_GATE_0_0} -quiet] -quiet

# IP: bd/mux/ip/mux_AND_GATE_0_1_2/mux_AND_GATE_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mux_AND_GATE_0_1 || ORIG_REF_NAME==mux_AND_GATE_0_1} -quiet] -quiet

# IP: bd/mux/ip/mux_AND_GATE_1_0_1/mux_AND_GATE_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mux_AND_GATE_1_0 || ORIG_REF_NAME==mux_AND_GATE_1_0} -quiet] -quiet

# IP: bd/mux/ip/mux_OR_GATE_0_0/mux_OR_GATE_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mux_OR_GATE_0_0 || ORIG_REF_NAME==mux_OR_GATE_0_0} -quiet] -quiet

# XDC: bd/mux/mux_ooc.xdc
