/*
 * This file was automatically generated by EvoSuite
 * Sat Nov 02 00:39:38 GMT 2019
 */

package net.mooctest;

import org.junit.Test;
import static org.junit.Assert.*;
import net.mooctest.EmptyQueueException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class EmptyQueueException_ESTest extends EmptyQueueException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      EmptyQueueException emptyQueueException0 = new EmptyQueueException("");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      EmptyQueueException emptyQueueException0 = new EmptyQueueException();
  }
}
