/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 16 07:11:09 GMT 2020
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MessageBuilder_ESTest extends MessageBuilder_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MessageBuilder messageBuilder0 = new MessageBuilder();
      String string0 = messageBuilder0.getMessage("*Fcq");
      assertEquals("Hello *Fcq", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MessageBuilder messageBuilder0 = new MessageBuilder();
      String string0 = messageBuilder0.getMessage("m");
      assertEquals("Hello m", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MessageBuilder messageBuilder0 = new MessageBuilder();
      String string0 = messageBuilder0.getMessage("6tr+RB52Tu");
      assertEquals("Too long: 6tr+RB52Tu", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      MessageBuilder messageBuilder0 = new MessageBuilder();
      String string0 = messageBuilder0.getMessage("");
      assertEquals("Please provide a name!", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      MessageBuilder messageBuilder0 = new MessageBuilder();
      // Undeclared exception!
      try { 
        messageBuilder0.getMessage((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }
}
