/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 19 08:24:13 GMT 2019
 */

package net.mooctest;

import org.junit.Test;
import static org.junit.Assert.*;
import net.mooctest.ExpressionParserException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ExpressionParserException_ESTest extends ExpressionParserException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ExpressionParserException expressionParserException0 = new ExpressionParserException((String) null);
      String string0 = expressionParserException0.getFaultyExpression();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ExpressionParserException expressionParserException0 = new ExpressionParserException("?b`|4&|x$");
      String string0 = expressionParserException0.getFaultyExpression();
      assertEquals("?b`|4&|x$", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ExpressionParserException expressionParserException0 = new ExpressionParserException("");
      String string0 = expressionParserException0.getFaultyExpression();
      assertEquals("", string0);
  }
}
