/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 19 08:24:37 GMT 2019
 */

package net.mooctest;

import org.junit.Test;
import static org.junit.Assert.*;
import net.mooctest.MissingOperandException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MissingOperandException_ESTest extends MissingOperandException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MissingOperandException missingOperandException0 = new MissingOperandException((String) null, (String) null);
      String string0 = missingOperandException0.getOperator();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MissingOperandException missingOperandException0 = new MissingOperandException("]|qZ", "lt^_~Y{lsV");
      String string0 = missingOperandException0.getOperator();
      assertEquals("lt^_~Y{lsV", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MissingOperandException missingOperandException0 = new MissingOperandException("", "");
      String string0 = missingOperandException0.getOperator();
      assertEquals("", string0);
  }
}
