/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 19 08:24:14 GMT 2019
 */

package net.mooctest;

import org.junit.Test;
import static org.junit.Assert.*;
import net.mooctest.UnmatchedBracketsException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class UnmatchedBracketsException_ESTest extends UnmatchedBracketsException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UnmatchedBracketsException unmatchedBracketsException0 = new UnmatchedBracketsException("", 0);
      int int0 = unmatchedBracketsException0.getIndexOfBracket();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      UnmatchedBracketsException unmatchedBracketsException0 = new UnmatchedBracketsException("fs()r$:Z", 1);
      int int0 = unmatchedBracketsException0.getIndexOfBracket();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      UnmatchedBracketsException unmatchedBracketsException0 = new UnmatchedBracketsException("", (-607));
      int int0 = unmatchedBracketsException0.getIndexOfBracket();
      assertEquals((-607), int0);
  }
}
