/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 16 07:11:09 GMT 2020
 */

import org.junit.Test;
import static org.junit.Assert.*;

public class MessageBuilder_ESTest {

  @Test(timeout = 4000)
  public void testL2a5a7a9a10a16a19()  throws Throwable  {
      MessageBuilder messageBuilder0 = new MessageBuilder();
      String string0 = messageBuilder0.getMessage("*Fcq");
      assertEquals("Hello *Fcq", string0);
  }

  @Test(timeout = 4000)
  public void testL2a5a7a9a10a16a19again()  throws Throwable  {
      MessageBuilder messageBuilder0 = new MessageBuilder();
      String string0 = messageBuilder0.getMessage("m");
      assertEquals("Hello m", string0);
  }

  @Test(timeout = 4000)
  public void testL2a5a7a9a11a14a16a19()  throws Throwable  {
      MessageBuilder messageBuilder0 = new MessageBuilder();
      String string0 = messageBuilder0.getMessage("6tr+RB52Tu");
      assertEquals("Too long: 6tr+RB52Tu", string0);
  }

  @Test(timeout = 4000)
  public void testL2a5a7a8a16a19()  throws Throwable  {
      MessageBuilder messageBuilder0 = new MessageBuilder();
      String string0 = messageBuilder0.getMessage("");
      assertEquals("Please provide a name!", string0);
  }

  @Test(timeout = 4000)
  public void testL2a5a7a8a16()  throws Throwable  {
      MessageBuilder messageBuilder0 = new MessageBuilder();
      // Undeclared exception!
      try { 
        messageBuilder0.getMessage((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }
}
