# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tfgg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Projects/vivado/assignment1/assignment1/assignment1.cache/wt [current_project]
set_property parent.project_path D:/Projects/vivado/assignment1/assignment1/assignment1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths d:/Projects/vivado [current_project]
set_property ip_output_repo d:/Projects/vivado/assignment1/assignment1/assignment1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib D:/Projects/vivado/assignment1/assignment1/assignment1.srcs/sources_1/new/demorgan_sd.v
read_ip -quiet d:/Projects/vivado/assignment1/assignment1/assignment1.srcs/sources_1/ip/orgate_0_1/orgate_0.xci

read_ip -quiet d:/Projects/vivado/assignment1/assignment1/assignment1.srcs/sources_1/ip/notgate_0/notgate_0.xci

read_ip -quiet d:/Projects/vivado/assignment1/assignment1/assignment1.srcs/sources_1/ip/andgate_0/andgate_0.xci

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Projects/vivado/assignment1/assignment1/assignment1.srcs/constrs_1/new/assignment2.xdc
set_property used_in_implementation false [get_files D:/Projects/vivado/assignment1/assignment1/assignment1.srcs/constrs_1/new/assignment2.xdc]


synth_design -top demorgan_sd -part xc7a100tfgg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef demorgan_sd.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file demorgan_sd_utilization_synth.rpt -pb demorgan_sd_utilization_synth.pb"
